# fly.toml app configuration file generated for kayjan on 2023-10-27T09:57:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "kayjan"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  image = "kayjan/test-app:latest"

[processes]
  app = ""

[[services]]
  protocol = "tcp"
  internal_port = 8060
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
