name: Fly Deploy
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin $${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build --no-cache --build-arg port=8060 -t ${{ secrets.DOCKERHUB_USERNAME }}/test-app:latest .
  push:
    name: Push Docker image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/test-app
  deploy:
      name: Deploy app
      needs: push
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
