name: Fly Deploy
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build --no-cache --build-arg port=8060 -t kayjan/test-app:latest .
      - run: docker push kayjan/test-app
  docker-login:
    name: Login to Docker Hub
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  push:
    name: Push Docker image
    needs: docker-login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker push kayjan/test-app
  deploy:
      name: Deploy app
      needs: push
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
